-- MySQL Script generated by MySQL Workbench
-- Tue Nov 25 14:33:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bairro` (
  `BairroID` INT NOT NULL AUTO_INCREMENT,
  `Nome_bairro` VARCHAR(45) NOT NULL,
  `Zona_cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BairroID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Coleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Coleta` (
  `ColetaId` INT NOT NULL,
  `Dia_coleta` VARCHAR(45) NOT NULL,
  `Horario_coleta` VARCHAR(45) NOT NULL,
  `Tipo_coleta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ColetaId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
